package HosterJail

const templateJailRunningConfigPartial = `# Running Jail config generated by Hoster
{{ .JailName }} {
    host.hostname = {{ .JailHostname }};
	vnet;
	vnet.interface = "{{ .IFaceB }}";
    path = "{{ .JailRootPath }}";
    exec.start = "{{ .StartupScript }}";
    exec.stop = "{{ .ShutdownScript }}";
    exec.consolelog = "/var/log/jail_console_{{ .JailName }}.log";

    # Log Jail startup and shutdown
    exec.prestart = "logger HOSTER_JAILS starting the Jail: {{ .JailName }}";
    exec.poststart = "logger HOSTER_JAILS the Jail has been started: {{ .JailName }}";
    exec.prestop = "logger HOSTER_JAILS stopping the Jail: {{ .JailName }}";
    exec.poststop = "logger HOSTER_JAILS the Jail has been stopped: {{ .JailName }}";

    # Apply Jail resource limits
    exec.poststart += "rctl -a jail:{{ .JailName }}:memoryuse:deny={{ .RAMLimit }}";
    exec.poststart += "rctl -a jail:{{ .JailName }}:memorylocked:deny={{ .RAMLimit }}";
    exec.poststart += "rctl -a jail:{{ .JailName }}:pcpu:deny={{ .CpuLimitReal }}";

	# Apply VNet network IP address
    exec.poststart += "jexec {{ .JailName }} ifconfig {{ .IFaceB }} inet {{ .IPAddress }}/{{ .Netmask }}";
    exec.poststart += "jexec {{ .JailName }} ifconfig {{ .IFaceB }} up";
    exec.poststart += "jexec {{ .JailName }} route add default {{ .DefaultRouter }}";

	# Cleanup the created resources
    exec.poststop += "rctl -r jail:{{ .JailName }}";
    exec.poststop += "ifconfig {{ .IFaceB }} destroy";
    exec.poststop += "umount {{ .JailRootPath }}/dev || logger 'HOSTER_JAILS could not unmount {{ .JailRootPath }}/dev'";

    # Apply timezone settings
    exec.poststart += "tzsetup -sC {{ .JailRootPath }} {{ .Timezone }}";

	# Misc
    exec.clean;
    stop.timeout = 10;

    # Additional config
`

const templateJailRcConf = `# Hoster generated RC.CONF
clear_tmp_enable="YES"
syslogd_flags="-ss"

# DISABLE ANY SENDMAIL ACTIVITY TO CUT THE START-UP TIME
sendmail_enable="NO"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"

`

const templateJailResolvConf = `# Hoster generated RESOLV.CONF
search {{ .Parent }}.lan
nameserver {{ .DnsServer }}
`
