// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Simple function, that returns this REST API server health status.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "REST API server health status.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    }
                }
            }
        },
        "/health/auth/any": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Check if ` + "`" + `any` + "`" + ` of the two users can log in. Useful for the routes which are required by both users: regular and HA.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check ` + "`" + `any` + "`" + ` user authentication.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/health/auth/ha": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Check the ` + "`" + `HA` + "`" + ` user authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check the ` + "`" + `HA` + "`" + ` user authentication.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/health/auth/regular": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Check the ` + "`" + `regular` + "`" + ` user authentication.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check the ` + "`" + `regular` + "`" + ` user authentication.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/host/info": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get Host info.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Both users are allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Host"
                ],
                "summary": "Get Host info.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HosterHostUtils.HostInfo"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/jail/all": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the list of all Jails, including the information about them.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Both users are allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jails"
                ],
                "summary": "List all Jails.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/HosterJailUtils.JailApi"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/jail/deploy": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Deploy a new Jail using a set of defined parameters.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Only ` + "`" + `rest` + "`" + ` user is allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jails"
                ],
                "summary": "Deploy a new Jail.",
                "parameters": [
                    {
                        "description": "Request payload",
                        "name": "Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/HosterJail.DeployInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/jail/destroy/{jail_name}": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "` + "`" + `DANGER` + "`" + ` - destructive operation!\u003cbr\u003e\u003cbr\u003eDestroy a specific Jail using it's name as a parameter.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Only ` + "`" + `rest` + "`" + ` user is allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jails"
                ],
                "summary": "Destroy a specific Jail.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jail Name",
                        "name": "jail_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/jail/info/{jail_name}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get Jail info.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Both users are allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jails"
                ],
                "summary": "Get Jail info.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jail Name",
                        "name": "jail_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/HosterJailUtils.JailApi"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/jail/start/{jail_name}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Start a specific Jail using it's name as a parameter.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Both users are allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jails"
                ],
                "summary": "Start a specific Jail.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jail Name",
                        "name": "jail_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/jail/stop/{jail_name}": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Stop a specific Jail using it's name as a parameter.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Both users are allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jails"
                ],
                "summary": "Stop a specific Jail.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Jail Name",
                        "name": "jail_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/jail/template/list": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Get the list of all Jail templates.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Only ` + "`" + `rest` + "`" + ` user is allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jails"
                ],
                "summary": "List all Jail templates.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/snapshot/all/{res_name}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "List all snapshots for any given VM or a Jail.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Both users are allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Snapshots"
                ],
                "summary": "List all snapshots for any given VM or a Jail.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Resource Name (Jail or VM)",
                        "name": "res_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/zfsutils.SnapshotInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/snapshot/destroy/{snapshot_name}": {
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Destroy a snapshot for any given VM or a Jail.\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Only ` + "`" + `rest` + "`" + ` user is allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Snapshots"
                ],
                "summary": "Destroy a snapshot for any given VM or a Jail.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Snapshot Name",
                        "name": "res_name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        },
        "/snapshot/take": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Take a new VM or Jail snapshot, using the resource name (Jail name or a VM name).\u003cbr\u003e` + "`" + `AUTH` + "`" + `: Only ` + "`" + `rest` + "`" + ` user is allowed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Snapshots"
                ],
                "summary": "Take a new snapshot.",
                "parameters": [
                    {
                        "description": "Request payload",
                        "name": "Input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.SnapshotInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerSuccess"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.SwaggerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "FreeBSDOsInfo.ArcInfo": {
            "type": "object",
            "properties": {
                "arc_used_bytes": {
                    "type": "integer"
                },
                "arc_used_human": {
                    "type": "string"
                }
            }
        },
        "FreeBSDOsInfo.CpuInfo": {
            "type": "object",
            "properties": {
                "cpu_arch": {
                    "type": "string"
                },
                "cpu_cores": {
                    "type": "integer"
                },
                "cpu_model": {
                    "type": "string"
                },
                "cpu_sockets": {
                    "type": "integer"
                },
                "cpu_threads": {
                    "type": "integer"
                },
                "overall_cpus": {
                    "type": "integer"
                }
            }
        },
        "FreeBSDOsInfo.RamInfo": {
            "type": "object",
            "properties": {
                "ram_free_bytes": {
                    "type": "integer"
                },
                "ram_free_human": {
                    "type": "string"
                },
                "ram_overall_bytes": {
                    "type": "integer"
                },
                "ram_overall_human": {
                    "type": "string"
                },
                "ram_used_bytes": {
                    "type": "integer"
                },
                "ram_used_human": {
                    "type": "string"
                }
            }
        },
        "FreeBSDOsInfo.SwapInfo": {
            "type": "object",
            "properties": {
                "swap_free_bytes": {
                    "type": "integer"
                },
                "swap_free_human": {
                    "type": "string"
                },
                "swap_overall_bytes": {
                    "type": "integer"
                },
                "swap_overall_human": {
                    "type": "string"
                },
                "swap_used_bytes": {
                    "type": "integer"
                },
                "swap_used_human": {
                    "type": "string"
                }
            }
        },
        "HosterHostUtils.HostInfo": {
            "type": "object",
            "properties": {
                "all_vms": {
                    "type": "integer"
                },
                "arc_info": {
                    "$ref": "#/definitions/FreeBSDOsInfo.ArcInfo"
                },
                "backup_vms": {
                    "type": "integer"
                },
                "cpu_info": {
                    "$ref": "#/definitions/FreeBSDOsInfo.CpuInfo"
                },
                "hostname": {
                    "type": "string"
                },
                "live_vms": {
                    "type": "integer"
                },
                "offline_vms": {
                    "type": "integer"
                },
                "offline_vms_prod": {
                    "type": "integer"
                },
                "ram_info": {
                    "$ref": "#/definitions/FreeBSDOsInfo.RamInfo"
                },
                "swap_info": {
                    "$ref": "#/definitions/FreeBSDOsInfo.SwapInfo"
                },
                "system_major_version": {
                    "type": "string"
                },
                "system_uptime": {
                    "type": "string"
                },
                "vcpu_2_pcpu_ratio": {
                    "type": "number"
                },
                "zpool_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/zfsutils.ZpoolInfo"
                    }
                }
            }
        },
        "HosterJail.DeployInput": {
            "type": "object",
            "properties": {
                "cpu_limit": {
                    "type": "integer"
                },
                "dataset_parent": {
                    "type": "string"
                },
                "dns_server": {
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                },
                "jail_name": {
                    "type": "string"
                },
                "network_name": {
                    "type": "string"
                },
                "ram_limit": {
                    "type": "string"
                },
                "release": {
                    "type": "string"
                }
            }
        },
        "HosterJailUtils.JailApi": {
            "type": "object",
            "properties": {
                "backup": {
                    "type": "boolean"
                },
                "config_file_append": {
                    "type": "string"
                },
                "cpu_limit_percent": {
                    "type": "integer"
                },
                "current_host": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dns_server": {
                    "type": "string"
                },
                "encrypted": {
                    "type": "boolean"
                },
                "ip_address": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "parent": {
                    "type": "string"
                },
                "production": {
                    "type": "boolean"
                },
                "ram_limit": {
                    "type": "string"
                },
                "release": {
                    "type": "string"
                },
                "running": {
                    "type": "boolean"
                },
                "shutdown_script": {
                    "type": "string"
                },
                "space_free_b": {
                    "type": "integer"
                },
                "space_free_h": {
                    "type": "string"
                },
                "space_used_b": {
                    "type": "integer"
                },
                "space_used_h": {
                    "type": "string"
                },
                "startup_script": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "uptime": {
                    "type": "string"
                }
            }
        },
        "handlers.SnapshotInput": {
            "type": "object",
            "properties": {
                "res_name": {
                    "type": "string"
                },
                "snapshot_type": {
                    "type": "string"
                },
                "snapshots_to_keep": {
                    "type": "integer"
                }
            }
        },
        "handlers.SwaggerError": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.SwaggerSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "success",
                    "type": "string"
                }
            }
        },
        "zfsutils.SnapshotInfo": {
            "type": "object",
            "properties": {
                "snapshot_clones": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "snapshot_dataset": {
                    "type": "string"
                },
                "snapshot_description": {
                    "type": "string"
                },
                "snapshot_locked": {
                    "type": "boolean"
                },
                "snapshot_name": {
                    "type": "string"
                },
                "snapshot_short_name": {
                    "type": "string"
                },
                "snapshot_size_bytes": {
                    "type": "integer"
                },
                "snapshot_size_human": {
                    "type": "string"
                }
            }
        },
        "zfsutils.ZpoolInfo": {
            "type": "object",
            "properties": {
                "allocated_bytes": {
                    "type": "integer"
                },
                "allocated_human": {
                    "type": "string"
                },
                "fragmentation": {
                    "type": "integer"
                },
                "free_bytes": {
                    "type": "integer"
                },
                "free_human": {
                    "type": "string"
                },
                "healthy": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "size_human": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api/v2",
	Schemes:          []string{},
	Title:            "Hoster Node REST API Docs",
	Description:      "REST API documentation for the `Hoster` nodes. This HTTP endpoint is located directly on the `Hoster` node.<br>Please, take some extra care with the things you execute here, because many of them can be destructive and non-revertible (e.g. vm destroy, snapshot rollback, host reboot, etc).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
