basePath: /api/v2
definitions:
  HosterJailUtils.JailApi:
    properties:
      backup:
        type: boolean
      config_file_append:
        type: string
      cpu_limit_percent:
        type: integer
      current_host:
        type: string
      description:
        type: string
      dns_server:
        type: string
      encrypted:
        type: boolean
      ip_address:
        type: string
      name:
        type: string
      network:
        type: string
      parent:
        type: string
      production:
        type: boolean
      ram_limit:
        type: string
      release:
        type: string
      running:
        type: boolean
      shutdown_script:
        type: string
      space_free_b:
        type: integer
      space_free_h:
        type: string
      space_used_b:
        type: integer
      space_used_h:
        type: string
      startup_script:
        type: string
      timezone:
        type: string
      uptime:
        type: string
    type: object
  handlers.Models_SimpleSuccess:
    properties:
      message:
        description: success
        type: string
    type: object
  handlers.SwaggerError:
    properties:
      id:
        type: integer
      message:
        type: string
    type: object
info:
  contact: {}
  description: REST API documentation for the `Hoster` nodes. This HTTP endpoint is
    located directly on the `Hoster` node.<br>Please, take some extra care with the
    things you execute here, because many of them can be destructive and non-revertible
    (e.g. vm destroy, snapshot rollback, host reboot, etc).
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Hoster Node REST API Docs
  version: "2.0"
paths:
  /health:
    get:
      description: Simple function, that returns this REST API server health status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Models_SimpleSuccess'
      summary: REST API server health status.
      tags:
      - Health
  /health/auth/any:
    get:
      description: 'Check if `any` of the two users can log in. Useful for the routes
        which are required by both users: regular and HA.'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Models_SimpleSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Check `any` user authentication.
      tags:
      - Health
  /health/auth/ha:
    get:
      description: Check the `HA` user authentication.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Models_SimpleSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Check the `HA` user authentication.
      tags:
      - Health
  /health/auth/regular:
    get:
      description: Check the `regular` user authentication.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.Models_SimpleSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Check the `regular` user authentication.
      tags:
      - Health
  /vm/all:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/HosterJailUtils.JailApi'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      summary: Get the list of all Jails, including the information about them.
      tags:
      - Jails
swagger: "2.0"
