basePath: /api/v2
definitions:
  FreeBSDOsInfo.ArcInfo:
    properties:
      arc_used_bytes:
        type: integer
      arc_used_human:
        type: string
    type: object
  FreeBSDOsInfo.CpuInfo:
    properties:
      cpu_arch:
        type: string
      cpu_cores:
        type: integer
      cpu_model:
        type: string
      cpu_sockets:
        type: integer
      cpu_threads:
        type: integer
      overall_cpus:
        type: integer
    type: object
  FreeBSDOsInfo.RamInfo:
    properties:
      ram_free_bytes:
        type: integer
      ram_free_human:
        type: string
      ram_overall_bytes:
        type: integer
      ram_overall_human:
        type: string
      ram_used_bytes:
        type: integer
      ram_used_human:
        type: string
    type: object
  FreeBSDOsInfo.SwapInfo:
    properties:
      swap_free_bytes:
        type: integer
      swap_free_human:
        type: string
      swap_overall_bytes:
        type: integer
      swap_overall_human:
        type: string
      swap_used_bytes:
        type: integer
      swap_used_human:
        type: string
    type: object
  HosterHostUtils.HostInfo:
    properties:
      all_vms:
        type: integer
      arc_info:
        $ref: '#/definitions/FreeBSDOsInfo.ArcInfo'
      backup_vms:
        type: integer
      cpu_info:
        $ref: '#/definitions/FreeBSDOsInfo.CpuInfo'
      hostname:
        type: string
      live_vms:
        type: integer
      offline_vms:
        type: integer
      offline_vms_prod:
        type: integer
      ram_info:
        $ref: '#/definitions/FreeBSDOsInfo.RamInfo'
      swap_info:
        $ref: '#/definitions/FreeBSDOsInfo.SwapInfo'
      system_major_version:
        type: string
      system_uptime:
        type: string
      vcpu_2_pcpu_ratio:
        type: number
      zpool_list:
        items:
          $ref: '#/definitions/zfsutils.ZpoolInfo'
        type: array
    type: object
  HosterJail.DeployInput:
    properties:
      cpu_limit:
        type: integer
      dataset_parent:
        type: string
      dns_server:
        type: string
      ip_address:
        type: string
      jail_name:
        type: string
      network_name:
        type: string
      ram_limit:
        type: string
      release:
        type: string
    type: object
  HosterJailUtils.JailApi:
    properties:
      backup:
        type: boolean
      config_file_append:
        type: string
      cpu_limit_percent:
        type: integer
      current_host:
        type: string
      description:
        type: string
      dns_server:
        type: string
      encrypted:
        type: boolean
      ip_address:
        type: string
      name:
        type: string
      network:
        type: string
      parent:
        type: string
      production:
        type: boolean
      ram_limit:
        type: string
      release:
        type: string
      running:
        type: boolean
      shutdown_script:
        type: string
      space_free_b:
        type: integer
      space_free_h:
        type: string
      space_used_b:
        type: integer
      space_used_h:
        type: string
      startup_script:
        type: string
      timezone:
        type: string
      uptime:
        type: string
    type: object
  handlers.SnapshotInput:
    properties:
      res_name:
        type: string
      snapshot_type:
        type: string
      snapshots_to_keep:
        type: integer
    type: object
  handlers.SwaggerError:
    properties:
      id:
        type: integer
      message:
        type: string
    type: object
  handlers.SwaggerSuccess:
    properties:
      message:
        description: success
        type: string
    type: object
  zfsutils.SnapshotInfo:
    properties:
      snapshot_clones:
        items:
          type: string
        type: array
      snapshot_dataset:
        type: string
      snapshot_description:
        type: string
      snapshot_locked:
        type: boolean
      snapshot_name:
        type: string
      snapshot_short_name:
        type: string
      snapshot_size_bytes:
        type: integer
      snapshot_size_human:
        type: string
    type: object
  zfsutils.ZpoolInfo:
    properties:
      allocated_bytes:
        type: integer
      allocated_human:
        type: string
      fragmentation:
        type: integer
      free_bytes:
        type: integer
      free_human:
        type: string
      healthy:
        type: boolean
      name:
        type: string
      size_bytes:
        type: integer
      size_human:
        type: string
    type: object
info:
  contact: {}
  description: REST API documentation for the `Hoster` nodes. This HTTP endpoint is
    located directly on the `Hoster` node.<br>Please, take some extra care with the
    things you execute here, because many of them can be destructive and non-revertible
    (e.g. vm destroy, snapshot rollback, host reboot, etc).
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Hoster Node REST API Docs
  version: "2.0"
paths:
  /health:
    get:
      description: Simple function, that returns this REST API server health status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
      summary: REST API server health status.
      tags:
      - Health
  /health/auth/any:
    get:
      description: 'Check if `any` of the two users can log in. Useful for the routes
        which are required by both users: regular and HA.'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Check `any` user authentication.
      tags:
      - Health
  /health/auth/ha:
    get:
      description: Check the `HA` user authentication.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Check the `HA` user authentication.
      tags:
      - Health
  /health/auth/regular:
    get:
      description: Check the `regular` user authentication.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Check the `regular` user authentication.
      tags:
      - Health
  /host/info:
    get:
      description: 'Get Host info.<br>`AUTH`: Both users are allowed.'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/HosterHostUtils.HostInfo'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Get Host info.
      tags:
      - Host
  /jail/all:
    get:
      description: 'Get the list of all Jails, including the information about them.<br>`AUTH`:
        Both users are allowed.'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/HosterJailUtils.JailApi'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: List all Jails.
      tags:
      - Jails
  /jail/deploy:
    post:
      description: 'Deploy a new Jail using a set of defined parameters.<br>`AUTH`:
        Only `rest` user is allowed.'
      parameters:
      - description: Request payload
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/HosterJail.DeployInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Deploy a new Jail.
      tags:
      - Jails
  /jail/destroy/{jail_name}:
    delete:
      description: '`DANGER` - destructive operation!<br><br>Destroy a specific Jail
        using it''s name as a parameter.<br>`AUTH`: Only `rest` user is allowed.'
      parameters:
      - description: Jail Name
        in: path
        name: jail_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Destroy a specific Jail.
      tags:
      - Jails
  /jail/info/{jail_name}:
    get:
      description: 'Get Jail info.<br>`AUTH`: Both users are allowed.'
      parameters:
      - description: Jail Name
        in: path
        name: jail_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/HosterJailUtils.JailApi'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Get Jail info.
      tags:
      - Jails
  /jail/start/{jail_name}:
    post:
      description: 'Start a specific Jail using it''s name as a parameter.<br>`AUTH`:
        Both users are allowed.'
      parameters:
      - description: Jail Name
        in: path
        name: jail_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Start a specific Jail.
      tags:
      - Jails
  /jail/stop/{jail_name}:
    post:
      description: 'Stop a specific Jail using it''s name as a parameter.<br>`AUTH`:
        Both users are allowed.'
      parameters:
      - description: Jail Name
        in: path
        name: jail_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Stop a specific Jail.
      tags:
      - Jails
  /jail/template/list:
    get:
      description: 'Get the list of all Jail templates.<br>`AUTH`: Only `rest` user
        is allowed.'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: List all Jail templates.
      tags:
      - Jails
  /snapshot/all/{res_name}:
    get:
      description: 'List all snapshots for any given VM or a Jail.<br>`AUTH`: Both
        users are allowed.'
      parameters:
      - description: Resource Name (Jail or VM)
        in: path
        name: res_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/zfsutils.SnapshotInfo'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: List all snapshots for any given VM or a Jail.
      tags:
      - Snapshots
  /snapshot/destroy/{snapshot_name}:
    delete:
      description: 'Destroy a snapshot for any given VM or a Jail.<br>`AUTH`: Only
        `rest` user is allowed.'
      parameters:
      - description: Snapshot Name
        in: path
        name: res_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Destroy a snapshot for any given VM or a Jail.
      tags:
      - Snapshots
  /snapshot/take:
    post:
      description: 'Take a new VM or Jail snapshot, using the resource name (Jail
        name or a VM name).<br>`AUTH`: Only `rest` user is allowed.'
      parameters:
      - description: Request payload
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/handlers.SnapshotInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Take a new snapshot.
      tags:
      - Snapshots
swagger: "2.0"
