basePath: /api/v2
definitions:
  HosterJail.DeployInput:
    properties:
      cpuLimit:
        type: integer
      dnsServer:
        type: string
      dsParent:
        type: string
      ipAddress:
        type: string
      jailName:
        type: string
      network:
        type: string
      ramLimit:
        type: string
      release:
        type: string
    type: object
  HosterJailUtils.JailApi:
    properties:
      backup:
        type: boolean
      config_file_append:
        type: string
      cpu_limit_percent:
        type: integer
      current_host:
        type: string
      description:
        type: string
      dns_server:
        type: string
      encrypted:
        type: boolean
      ip_address:
        type: string
      name:
        type: string
      network:
        type: string
      parent:
        type: string
      production:
        type: boolean
      ram_limit:
        type: string
      release:
        type: string
      running:
        type: boolean
      shutdown_script:
        type: string
      space_free_b:
        type: integer
      space_free_h:
        type: string
      space_used_b:
        type: integer
      space_used_h:
        type: string
      startup_script:
        type: string
      timezone:
        type: string
      uptime:
        type: string
    type: object
  handlers.SwaggerError:
    properties:
      id:
        type: integer
      message:
        type: string
    type: object
  handlers.SwaggerSuccess:
    properties:
      message:
        description: success
        type: string
    type: object
info:
  contact: {}
  description: REST API documentation for the `Hoster` nodes. This HTTP endpoint is
    located directly on the `Hoster` node.<br>Please, take some extra care with the
    things you execute here, because many of them can be destructive and non-revertible
    (e.g. vm destroy, snapshot rollback, host reboot, etc).
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Hoster Node REST API Docs
  version: "2.0"
paths:
  /health:
    get:
      description: Simple function, that returns this REST API server health status.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
      summary: REST API server health status.
      tags:
      - Health
  /health/auth/any:
    get:
      description: 'Check if `any` of the two users can log in. Useful for the routes
        which are required by both users: regular and HA.'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Check `any` user authentication.
      tags:
      - Health
  /health/auth/ha:
    get:
      description: Check the `HA` user authentication.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Check the `HA` user authentication.
      tags:
      - Health
  /health/auth/regular:
    get:
      description: Check the `regular` user authentication.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Check the `regular` user authentication.
      tags:
      - Health
  /jail/all:
    get:
      description: 'Get the list of all Jails, including the information about them.<br>`AUTH`:
        Both users are allowed.'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/HosterJailUtils.JailApi'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: List all Jails.
      tags:
      - Jails
  /jail/deploy:
    post:
      description: 'Deploy a new Jail using a set of defined parameters.<br>`AUTH`:
        Only `rest` user is allowed.'
      parameters:
      - description: Request payload
        in: body
        name: Input
        required: true
        schema:
          $ref: '#/definitions/HosterJail.DeployInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Deploy a new Jail.
      tags:
      - Jails
  /jail/destroy/{jail_name}:
    delete:
      description: 'Destroy a specific Jail using it''s name as a parameter.<br>`DANGER`
        - destructive operation!<br>`AUTH`: Only `rest` user is allowed.'
      parameters:
      - description: Jail Name
        in: path
        name: jail_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Destroy a specific Jail.
      tags:
      - Jails
  /jail/info/{jail_name}:
    get:
      description: 'Get Jail info.<br>`AUTH`: Both users are allowed.'
      parameters:
      - description: Jail Name
        in: path
        name: jail_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/HosterJailUtils.JailApi'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Get Jail info.
      tags:
      - Jails
  /jail/start/{jail_name}:
    post:
      description: 'Start a specific Jail using it''s name as a parameter.<br>`AUTH`:
        Both users are allowed.'
      parameters:
      - description: Jail Name
        in: path
        name: jail_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Start a specific Jail.
      tags:
      - Jails
  /jail/stop/{jail_name}:
    post:
      description: 'Stop a specific Jail using it''s name as a parameter.<br>`AUTH`:
        Both users are allowed.'
      parameters:
      - description: Jail Name
        in: path
        name: jail_name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.SwaggerSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: Stop a specific Jail.
      tags:
      - Jails
  /jail/templates:
    get:
      description: 'Get the list of all Jail templates.<br>`AUTH`: Only `rest` user
        is allowed.'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.SwaggerError'
      security:
      - BasicAuth: []
      summary: List all Jail templates.
      tags:
      - Jails
swagger: "2.0"
