package cmd

import (
	"encoding/json"
	"errors"
	"log"
	"os"
	"text/template"

	"github.com/spf13/cobra"
)

var (
	jailStartCmd = &cobra.Command{
		Use:   "start",
		Short: "Start a specific Jail",
		Long:  `Start a specific Jail using it's name`,
		Args:  cobra.ExactArgs(1),
		Run: func(cmd *cobra.Command, args []string) {
			err := checkInitFile()
			if err != nil {
				log.Fatal(err.Error())
			}
			// cmd.Help()

			err = jailStart(args[0])
			if err != nil {
				log.Fatal(err.Error())
			}
		},
	}
)

func jailStart(jailName string) error {
	jailConfig, err := getJailConfig(jailName)
	if err != nil {
		return err
	}

	t, err := template.New("jailRunningConfigPartialTemplate").Parse(jailRunningConfigPartialTemplate)
	if err != nil {
		return err
	}

	err = t.Execute(os.Stdout, jailConfig)
	if err != nil {
		return err
	}

	return nil
}

const jailRunningConfigPartialTemplate = `# Running Jail config generated by Hoster
{{ .JailName }} {
    host.hostname = {{ .JailName }};
    ip4.addr = "vm-{{ .Network }}|{{ .IPAddress }}/{{ .Netmask }}";
    path = "{{ .JailRootPath }}";
    exec.clean;
    exec.start = "{{ .StartupScript }}";
    exec.stop = "{{ .ShutdownScript }}";
	# Additional config
`

func checkIfJailExists(jailName string) (jailExists bool) {
	datasets, err := getZfsDatasetInfo()
	if err != nil {
		return
	}

	for _, v := range datasets {
		if FileExists(v.MountPoint + "/" + jailName + "/jail_config.json") {
			return true
		}
	}

	return
}

func getJailConfig(jailName string) (jailConfig JailConfigFileStruct, configError error) {
	if !checkIfJailExists(jailName) {
		configError = errors.New("jail doesn't exist")
		return
	}

	datasets, err := getZfsDatasetInfo()
	if err != nil {
		configError = err
		return
	}

	configFile := ""
	for _, v := range datasets {
		if FileExists(v.MountPoint + "/" + jailName + "/jail_config.json") {
			configFile = v.MountPoint + "/" + jailName + "/jail_config.json"
			jailConfig.JailRootPath = v.MountPoint + "/" + jailName + "/"
		}
	}

	configFileRead, err := os.ReadFile(configFile)
	if err != nil {
		configError = err
		return
	}

	unmarshalErr := json.Unmarshal(configFileRead, &jailConfig)
	if unmarshalErr != nil {
		configError = unmarshalErr
		return
	}

	jailConfig.JailName = jailName
	jailConfig.Netmask = "24"

	return
}
