// Copyright 2023 Hoster Authors. All rights reserved.
// Use of this source code is governed by an Apache License 2.0
// license that can be found in the LICENSE file.

package HosterJailUtils

const TemplateJailRunningConfigPartial = `# Running Jail config generated by Hoster
{{ .JailName }} {
    # Initialize the Jail
    host.hostname = {{ .JailHostname }};
    vnet;
    vnet.interface = "{{ .IFaceB }}";
    path = "{{ .JailRootPath }}";
    exec.start = "{{ .StartupScript }}";
    exec.stop = "{{ .ShutdownScript }}";
    exec.consolelog = "/var/log/jail_console_{{ .JailName }}.log";

    # Log Jail's startup and shutdown
    # exec.prestart = "logger HOSTER_JAILS initializing start operation: {{ .JailName }}";
    # exec.poststart = "logger HOSTER_JAILS Jail is now up: {{ .JailName }}";
    # exec.prestop = "logger HOSTER_JAILS initializing stop operation: {{ .JailName }}";
    # exec.poststop = "logger HOSTER_JAILS Jail has been stopped: {{ .JailName }}";

    # Apply Jail resource limits
    exec.poststart += "rctl -a jail:{{ .JailName }}:memoryuse:deny={{ .RAMLimit }}";
    exec.poststart += "rctl -a jail:{{ .JailName }}:memorylocked:deny={{ .RAMLimit }}";
    exec.poststart += "rctl -a jail:{{ .JailName }}:pcpu:deny={{ .CpuLimitReal }}";

    # Apply VNet network IP address
    exec.poststart += "jexec {{ .JailName }} ifconfig {{ .IFaceB }} inet {{ .IPAddress }}/{{ .Netmask }}";
    exec.poststart += "jexec {{ .JailName }} ifconfig {{ .IFaceB }} up";
    exec.poststart += "jexec {{ .JailName }} route add default {{ .DefaultRouter }}";

    # Cleanup the created resources
    exec.poststop += "rctl -r jail:{{ .JailName }}";
    exec.poststop += "ifconfig {{ .IFaceA }} destroy";
    # exec.poststop += "umount {{ .JailRootPath }}/dev || logger 'HOSTER_JAILS could not unmount {{ .JailRootPath }}/dev for {{ .JailName }}'";

    # Apply the timezone settings
    exec.poststart += "tzsetup -sC {{ .JailRootPath }} {{ .Timezone }}";

    # Misc
    exec.clean;
    stop.timeout = 10;

    # Additional config
`

const TemplateJailRcConf = `# Hoster generated RC.CONF
clear_tmp_enable="YES"
syslogd_flags="-ss"

# DISABLE ANY SENDMAIL ACTIVITY TO CUT THE START-UP TIME
sendmail_enable="NO"
sendmail_submit_enable="NO"
sendmail_outbound_enable="NO"
sendmail_msp_queue_enable="NO"

`

const TemplateJailResolvConf = `# Hoster generated RESOLV.CONF
search {{ .Parent }}.lan
nameserver {{ .DnsServer }}
`
